Fix corelib build for WEC7.
Qt5 backported fix http://codereview.qt-project.org/17852 broke the Qt4.8
build for WEC7. The change works fine in Qt5 because Qt5 does not anymore
have QT_MODULE macro in every header, including qfunctions_wince.h.
See commit: 4ecf8279

Apparently implementations of QT_MODULE and c-language zlib are
not compatible, because MSVC2008 gives a lot of errors like:
    error C2085: 'qt_wince_getenv_s' : not in formal parameter list

Build break fixed by putting QT_MODULE macro inside #ifdef __cplusplus.

Change-Id: Id71386867750fcc61ab2cb2ecc527edc37c943ba
Reviewed-by: Andreas Holzammer <andreas.holzammer@kdab.com>
Reviewed-by: Friedemann Kleint <Friedemann.Kleint@nokia.com>